### ISSUE TITLE
"Reply" not working in p.a.d 3.2/Plone 5.2RC3

### ISSUE THREAD

**Issue by zopyx** [plone/plone.app.discussion#157]
The "Reply" button is supposed to unhide/open the textarea/form for a reply.

This does not work in Plone 5.2rc3.

Tested and reproducible on www.plone-demo.info

**Comment by tisto** [comment]
@zopyx any tracebacks in python or js?

**Comment by zopyx** [comment]
nothing

**Comment by pbauer** [comment]
Confirmed. The js `comment.js` is not part of the legacy-bundle and thus not there. 
I tried to fix that in #158 but got stuck.

**Comment by pbauer** [comment]
I guess this also needs a upgrade-step.

**Comment by pbauer** [comment]
I see the same problem with a other addons that use legacy js (e.g. eea.facetednavigation)

**Comment by pbauer** [comment]
https://github.com/plone/plone.app.discussion/pull/158 in combination with https://github.com/plone/Products.CMFPlone/pull/2899 fixes this.

I'm nor sure if this requires a upgrade-step.

**Comment by thet** [comment]
@pbauer see my comment in: https://github.com/plone/plone.app.discussion/pull/158#issuecomment-505327932

**Comment by pbauer** [comment]
https://github.com/plone/plone.app.discussion/pull/158 alone should fix the issue now.
Upgrade-step is added and CMFPlone profile version is bumped to run that step when updating Plone (https://github.com/plone/Products.CMFPlone/pull/2902 and https://github.com/plone/plone.app.upgrade/pull/211)
