### ISSUE TITLE
(re)move translations?

### ISSUE THREAD

**Issue by gforcada** [plone/plone.app.discussion#205]
@erral you might know better than me 🍀 

While running `codespell` in this repository, oh surprise, the translations in [`i18n`](https://github.com/plone/plone.app.discussion/tree/master/plone/app/discussion/i18n) folder produce false positives.

While `codespell` does [not ignore `.po` files by default](https://github.com/codespell-project/codespell/issues/2790), we have to find a solution.

But back to the point, are those translations there actually being used? 🤔 

The only `MessageFactory` that is created is for `plone`:

```bash
plone/app/discussion/__init__.py:1:from zope.i18nmessageid import MessageFactory
plone/app/discussion/__init__.py:4:_ = MessageFactory("plone")
```

So the translations in the `i18n` could be removed or merged/migrated to `plone.app.locales`? 🤔 

TIA! 🙇🏾

**Comment by erral** [comment]
The i18n folder is not used at all, we use the locales folder for ages...

Moreover the translations of p.a.discussion are included in p.a.locales see https://github.com/plone/buildout.coredev/blob/6.0/experimental/i18n.cfg#L46

**Comment by gforcada** [comment]
Ok, then I will remove that folder 👍🏾
