### ISSUE TITLE
Provide HCaptcha for plone.app.discussion

### ISSUE THREAD

**Issue by ksuess** [plone/plone.app.discussion#230]
… if plone.formwidget.hcaptcha is installed

**Comment by ksuess** [comment]
Fixed with 
- https://github.com/plone/plone.app.discussion/pull/232 for latest version (4.x)
- https://github.com/plone/plone.app.discussion/pull/229 for version 3.4.x for Plone 5.2

**Comment by ksuess** [comment]
Can we get releases for 3.4.x and 4.x please, @mauritsvanrees, thank you.

**Comment by mauritsvanrees** [comment]
@ksuess Thanks for your work!  I have released 3.4.8 and 4.1.0.
