### ISSUE TITLE
Move translations to plone.app.locales.

### ISSUE THREAD

**Issue by tisto** [plone/plone.app.discussion#66]

**Comment by tisto** [comment]
@vincentfretin plone.app.discussion uses its own domain:

https://github.com/plone/plone.app.discussion/blob/master/plone/app/discussion/locales/de/LC_MESSAGES/plone.app.discussion.po#L15

How would you suggest that we proceed?

**Comment by vincentfretin** [comment]
The simplest way is just to move all the content of the locales folder of plone.app.discussion master to the locales folder of plone.app.locales master I guess, and remove i18n:registerTranslations from configure.zcml.
We have plone.app.locales 4.3.x branch and master which target Plone 5.

**Comment by nilbacardit26** [comment]
I just ended up here to modify the translations of some messages. 

Thanks :)
