### ISSUE TITLE
 no email validation on anonymous comments

### ISSUE THREAD

**Issue by jensens** [plone/plone.app.discussion#73]
see plone/Products.CMFPlone#1055

**Comment by ksuess** [comment]
I am interested in email validation and would prepare a change.

Is there any reasons not to validate this field? Just asking, because this "issue" is not new.

**Comment by jensens** [comment]
Yes, please fix it. This one is not critical and nobody fixed it. If you need any guidance do not hesitate to ask.

**Comment by ksuess** [comment]
@jensens Would you please be so kind and check and merge. Thank you!
https://github.com/plone/plone.app.discussion/pull/124
