### ISSUE TITLE
Button "Edit" not translated

### ISSUE THREAD

**Issue by serge73** [plone/plone.app.discussion#90]
"Edit" not translated (line 124  /browser/comments.pt)
![2016-04-07_9-47-07](https://cloud.githubusercontent.com/assets/13430305/14340975/779586fa-fca6-11e5-8d36-615a160b32f0.jpg)

```
                          <!-- plone 5 will have auth_token available
                               so we'll use modal pattern -->
                          <a class="commentactionsform pat-plone-modal context"
                             tal:condition="auth_token"
                             tal:attributes="href string:${reply/absolute_url}/@@edit-comment?_authenticator=${auth_token}">Edit</a>
```

"form name="edit"" not used.
![2016-04-07_9-55-01](https://cloud.githubusercontent.com/assets/13430305/14341017/fd623184-fca6-11e5-9c56-1e4ec3a2643d.jpg)

Plone 5.0.3 , plone.app.discussion 2.4.11

**Comment by gforcada** [comment]
@serge73 thanks for reporting (keep them coming)!

The fix is trivial, see #91
